# Project information
site_name: PyStarter
site_description: "Навчальний курс з програмування мовою Python. Необхідне."
site_author : "Ruslan Iskov"
site_url: "http://ruslan.rv.ua/PyStarter"

use_directory_urls: false
strict: true
# dev_addr: '127.0.0.1:8010'

# site_dir: '.\docs'
# docs_dir: '.\source'

# Copyright
copyright: "Copyright &copy; Ruslan Iskov <ruslan.rv.ua@gmail.com>"

# Configuration
theme:
  name: material
  language: uk
  icon:
    logo: material/language-python
    # logo: fontawesome/brands/python
  # favicon: fontawesome/brands/python.svg
  palette:
    scheme: slate # or "default"
    primary: 'black'
    accent: 'yellow'
  features:
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.footer
    # or - navigation.tabs
    # or - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    # - toc.integrate
    # - navigation.indexes
    # - navigation.top # totop button
    - navigation.prune

# css overrides to make high contrast theme
extra_css:
  - _stylesheets/dark_theme.css
  - _stylesheets/codehilite.css
  - _stylesheets/fixes.css


# switch off plugins, it's for removing 'search' feature
# plugins: []
plugins:
  - offline
 # - search
 # - awesome-pages:
   # collapse_single_pages: true

# Customization
extra:
  # disqus: <shortname>
  generator: false
  social:
   - icon: fontawesome/brands/github
     link: https://github.com/ruslan-rv-ua/pystarter
#    search:
#        language: 'en, ru'
    

# Google Analytics
# google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  # - toc:
      # permalink: false
      # slugify: !!python/name:pymdownx.slugs.uslugify
      # toc_depth: 3
  - admonition
  # - codehilite:
  #     guess_lang: false
  #     css_class: codehilite
  #     # pygments_style: agate
  # - meta
  # - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.tilde

nav:
  - Про цей курс: index.md
  - Міфи про навчання: miths_about_education.md
  - Мова програмування Python: about_python.md
  - 01. Підготовка:
    - Операційна система: preparations/os.md
    - Інтерпретатор Python: preparations/interpreter.md
    - Засоби розробки: preparations/editor.md
    - Перегляд коду: preparations/telecode.md
    - Скрінрідер: preparations/screenreader.md
    - Інтерактивний режим інтерпретатора Python: preparations/console.md
  - 02. Типи даних. Змінні:
    - Типи даних: vars_and_types/types.md
    - Числа: vars_and_types/numbers.md
    - Змінні: vars_and_types/vars.md
    - Вирази та інструкції: vars_and_types/statement_and_expression.md
    ### - Завдання: vars_and_types/problems.md
  - 03. Python-програми:
    - Початковий код: source_code/source_code.md
    - Виконання програм: source_code/run_program.md
    - Вивід результатів: source_code/print.md
    - Коментарі: source_code/comments.md
  - 04. Символьні рядки:
    - Тип даних str: strings/strings.md
    - Екрановані послідовності: strings/escapes.md
    - Операції над символьними рядками: strings/strings_operations.md
    - Індексація: strings/indexing.md
  - 05. Функції:
    - Виклик функцій: functions/functions.md
    - Функції та вирази: functions/functions_exprs.md
    - Перетворення типів: functions/types_convertion.md
  - 06. Логіка:
    - Тип даних bool: bool_logic/bool.md
    - Логічні вирази: bool_logic/bool_expressions.md
  - 07. Розгалуження:
    - Інструкція if: if/if_statement.md
    - Інструкція else: if/else_statement.md
    - Інструкція elif: if/elif_statement.md
    - Тернарний умовний оператор: if/ternar_if.md
  - 08. Створення функцій:
    - Функції у програмуванні: functions_def/functions_explained.md
    - Визначення функцій: functions_def/functions_def.md
    - Параметри і аргументи: functions_def/functions_params.md
    - Повернення значень: functions_def/functions_return.md
    - Іменування функцій: functions_def/functions_naming.md
    - Локальні та глобальні змінні: functions_def/local_global_vars.md
  - 09. Цикли:
    - Цикли у програмуванні: loop_while/loops.md
    - Інструкція while: loop_while/while.md
    - Синтаксичний цукор: loop_while/syntax_sugar.md
    - Прийоми використання циклів: loop_while/usage.md
  - 10. Послідовності:
    - Тип даних list: sequences/list.md
    - Тип даних tuple: sequences/tuple.md
    - Вкладені структури даних: sequences/complex_structures.md
    - Послідовності в Python: sequences/sequences.md
  - 11. Об'єкти в Python:
    - Об'єкти і змінні: objects/objects_and_vars.md
    - Мутабельність: objects/mutability.md
    - Немутабельні винятки: objects/immutable_exceptions.md
    - Посилання у контейнерах: objects/containers_bindings.md
  - 12. Цикли 2:
    - Цикл for: loop_for/for.md
    - Тип даних range: loop_for/range.md
    - Прийоми використання for: loop_for/usage.md
    - Керування циклами: loop_for/loop_flow.md
  - 13. Методи:
    - Методи в Python: methods/methods.md
    - Методи символьних рядків: methods_str/str_methods.md
    - Форматування символьних рядків: methods_str/str_format.md
  - 14. Методи списків: 
    - Методи списків: methods_list/list_methods.md
  #   - Структура даних "стек": methods_list/stack.md
  - 15. Словники:
    - Тип даних dict: dict/dict.md
  #   - Методи словників: dict/dict_methods.md
  #   - Обхід словників: dict/dict_traversal.md
  # - 16. Файли:
  #   - Кодування текстової інформації: text_files/unicode.md
  #   - Текстові файли: text_files/open_close_flush.md
  #   - Читання і запис текстових файлів: text_files/read_write.md
  - 17. Модулі:
    - Модулі в Python: modules/modules.md
    - Використання модулів: modules/module_usage.md
    - Створення модулів: modules/module_composing.md
    # - math: modules/math_module.md
    - Модуль random: modules/random_module.md
    # - Модуль pprint: modules/pprint_module.md
  - Батарейки:
    - Модуль random: modules/random_module.md
  - Дзен: zen.md
  - Корисні ресурси: resources.md
  # - "Що далі?": next_steps.md